{

  const char* dirBase = "Rint:/";
  gDirectory->cd(dirBase);
  gStyle->SetOptStat(kFALSE);
  gStyle->SetErrorX(0.);
  
  // open test file
//   TFile* file = new TFile("output/TQAFLayer1Output-RelValTTbar-CMSSW_1_6_7.root");
  TFile* file = new TFile("output/TQAFLayer1Output-RelValTTbar-CMSSW_1_6_7-iniResTQAF.root");
//   TFile* file = new TFile("output/TQAFLayer1Output-RelValTTbar-CMSSW_1_6_7-iniResOwn.root");
  // alias electrons' branches
  Events->SetAlias("el"     , "TopElectrons_selectedLayer1TopElectrons__TQAF.obj");
  Events->SetAlias("elMoved", "TopElectrons_movedTopElectrons__TQAF.obj");
  // alias muons' branches
  Events->SetAlias("mu"     , "TopMuons_selectedLayer1TopMuons__TQAF.obj");
  Events->SetAlias("muMoved", "TopMuons_movedTopMuons__TQAF.obj");
  // alias taus' branches
  Events->SetAlias("tau"     , "TopTaus_selectedLayer1TopTaus__TQAF.obj");
  Events->SetAlias("tauMoved", "TopTaus_movedTopTaus__TQAF.obj");
  // alias jets' branches
  Events->SetAlias("jet"     , "TopJets_selectedLayer1TopJets__TQAF.obj");
  Events->SetAlias("jetMoved", "TopJets_movedTopJets__TQAF.obj");
  // alias METs' branches
  Events->SetAlias("met"     , "TopMETs_selectedLayer1TopMETs__TQAF.obj");
  Events->SetAlias("metMoved", "TopMETs_movedTopMETs__TQAF.obj");
  
  const Int_t    bins      =         50;
  const Double_t phiXmin   = -TMath::Pi(), phiXmax   = TMath::Pi(),
                 thetaXmin =          0. , thetaXmax = TMath::Pi(),
                 etaXmin   =         -2.5, etaXmax   =         2.5;

  // Draw electron angles                    
  TH1D* hElPhi        = new TH1D("hElPhi"       ,";#phi;electrons;"  ,bins,phiXmin  ,phiXmax);
  TH1D* hElMovedPhi   = new TH1D("hElMovedPhi"  ,";#phi;electrons;"  ,bins,phiXmin  ,phiXmax);
  TH1D* hElTheta      = new TH1D("hElTheta"     ,";#theta;electrons;",bins,thetaXmin,thetaXmax);
  TH1D* hElMovedTheta = new TH1D("hElMovedTheta",";#theta;electrons;",bins,thetaXmin,thetaXmax);
  TH1D* hElEta        = new TH1D("hElEta"       ,";#eta;electrons;"  ,bins,etaXmin  ,etaXmax);
  TH1D* hElMovedEta   = new TH1D("hElMovedEta"  ,";#eta;electrons;"  ,bins,etaXmin  ,etaXmax);
  TH2D* hElPhiMoved   = new TH2D("hElPhiMoved"  ,";#phi;#phi_{new};electrons"    ,bins,phiXmin  ,phiXmax  ,bins,phiXmin  ,phiXmax);
  TH2D* hElThetaMoved = new TH2D("hElThetaMoved",";#theta;#theta_{new};electrons",bins,thetaXmin,thetaXmax,bins,thetaXmin,thetaXmax);
  TH2D* hElEtaMoved   = new TH2D("hElEtaMoved"  ,";#eta;#eta_{new};electrons"    ,bins,etaXmin  ,etaXmax  ,bins,etaXmin  ,etaXmax);
  TH2D* hElRelDevPhi   = new TH2D("hElRelDevPhi"  ,";#phi;#phi_{new}-#phi;electrons"      ,bins,phiXmin  ,phiXmax  ,bins,-0.005,0.005);
  TH2D* hElRelDevTheta = new TH2D("hElRelDevTheta",";#theta;#theta_{new}-#theta;electrons",bins,thetaXmin,thetaXmax,bins,-0.005,0.005);
  TH2D* hElRelDevEta   = new TH2D("hElRelDevEta"  ,";#eta;#eta_{new}-#eta;electrons"      ,bins,etaXmin  ,etaXmax  ,bins,-0.005,0.005);
  hElPhi->SetLineColor(kRed);
  hElPhi->SetFillColor(kYellow);
  hElMovedPhi->SetLineWidth(2);
  hElTheta->SetLineColor(kRed);
  hElTheta->SetFillColor(kYellow);
  hElMovedTheta->SetLineWidth(2);
  hElEta->SetLineColor(kRed);
  hElEta->SetFillColor(kYellow);
  hElMovedEta->SetLineWidth(2);
  hElPhiMoved->SetMarkerSize(0.1);  
  hElThetaMoved->SetMarkerSize(0.1);
  hElEtaMoved->SetMarkerSize(0.1);  
  hElRelDevPhi->SetMarkerSize(0.1);  
  hElRelDevTheta->SetMarkerSize(0.1);
  hElRelDevEta->SetMarkerSize(0.1);  
  TCanvas* cElAngles = new TCanvas("cElAngles","Electron Angles");
  cElAngles->Divide(3,3);
  cElAngles->cd(1);
  Events->Draw("el.phi()>>hElPhi");
  Events->Draw("elMoved.phi()>>hElMovedPhi","","Same");
  cElAngles->cd(2);
  Events->Draw("el.theta()>>hElTheta");
  Events->Draw("elMoved.theta()>>hElMovedTheta","","Same");
  cElAngles->cd(3);
  Events->Draw("el.eta()>>hElEta");
  Events->Draw("elMoved.eta()>>hElMovedEta","","Same");
  cElAngles->cd(4);
  Events->Draw("elMoved.phi():el.phi()>>hElPhiMoved");
  cElAngles->cd(5);
  Events->Draw("elMoved.theta():el.theta()>>hElThetaMoved");
  cElAngles->cd(6);
  Events->Draw("elMoved.eta():el.eta()>>hElEtaMoved");
  cElAngles->cd(7);
  Events->Draw("elMoved.phi()-el.phi():el.phi()>>hElRelDevPhi");
  cElAngles->cd(8);
  Events->Draw("elMoved.theta()-el.theta():el.theta()>>hElRelDevTheta");
  cElAngles->cd(9);
  Events->Draw("elMoved.eta()-el.eta():el.eta()>>hElRelDevEta");
  // Draw electron resolutions                    
  TH1D* hElResPhi   = new TH1D("hElResPhi"  ,";#sigma_{#phi};electrons;"  ,bins,0.,0.0025);
  TH1D* hElResTheta = new TH1D("hElResTheta",";#sigma_{#theta};electrons;",bins,0.,0.001);
  TH1D* hElResEta   = new TH1D("hElResEta"  ,";#sigma_{#eta};electrons;"  ,bins,0.,0.001);
  TH2D* hElResAnglePhi   = new TH2D("hElResAnglePhi"  ,";#theta;#sigma_{#phi};electrons"   ,bins,thetaXmin,thetaXmax,bins,0.,0.0025);
  TH2D* hElResAngleTheta = new TH2D("hElResAngleTheta",";#theta;#sigma_{#theta};electrons;",bins,thetaXmin,thetaXmax,bins,0.,0.001);
  TH2D* hElResAngleEta   = new TH2D("hElResAngleEta"  ,";#theta;#sigma_{#eta};electrons;"  ,bins,thetaXmin,thetaXmax,bins,0.,0.001);
  TH1D* hElRelDevAngleResPhi   = new TH1D("hElRelDevAngleResPhi"  ,";#frac{#phi_{new}-#phi}{#sigma_{#phi}};electrons;"      ,bins,-10.,10.);
  TH1D* hElRelDevAngleResTheta = new TH1D("hElRelDevAngleResTheta",";#frac{#theta_{new}-#theta}{#sigma_{#theta}};electrons;",bins,-10.,10.);
  TH1D* hElRelDevAngleResEta   = new TH1D("hElRelDevAngleResEta"  ,";#frac{#eta_{new}-#eta}{#sigma_{#eta}};electrons;"      ,bins,-10.,10.);
  TH2D* hElRelDevResPhi   = new TH2D("hElRelDevResPhi"  ,";#sigma_{#phi};#frac{#phi_{new}-#phi}{#sigma_{#phi}};electrons"        ,bins,0.,0.0025,bins,-10.,10.);
  TH2D* hElRelDevResTheta = new TH2D("hElRelDevResTheta",";#sigma_{#theta};#frac{#theta_{new}-#theta}{#sigma_{#theta}};electrons",bins,0.,0.001 ,bins,-10.,10.);
  TH2D* hElRelDevResEta   = new TH2D("hElRelDevResEta"  ,";#sigma_{#eta};#frac{#eta_{new}-#eta}{#sigma_{#eta}};electrons"        ,bins,0.,0.001 ,bins,-10.,10.);
  hElResAnglePhi->SetMarkerSize(0.1);  
  hElResAngleTheta->SetMarkerSize(0.1);
  hElResAngleEta->SetMarkerSize(0.1);  
  hElRelDevResPhi->SetMarkerSize(0.1);  
  hElRelDevResTheta->SetMarkerSize(0.1);
  hElRelDevResEta->SetMarkerSize(0.1);  
  TCanvas* cElRes= new TCanvas("cElRes","Electron Resolutions");
  cElRes->Divide(3,4);
  cElRes->cd(1);
  Events->Draw("el.getResPhi()>>hElResPhi");
  cElRes->cd(2);
  Events->Draw("el.getResTheta()>>hElResTheta");
  cElRes->cd(3);
  Events->Draw("el.getResEta()>>hElResEta");
  cElRes->cd(4);
  Events->Draw("el.getResPhi():el.theta()>>hElResAnglePhi");
  cElRes->cd(5);
  Events->Draw("el.getResTheta():el.theta()>>hElResAngleTheta");
  cElRes->cd(6);
  Events->Draw("el.getResEta():el.theta()>>hElResAngleEta");
  cElRes->cd(7);
  Events->Draw("(elMoved.phi()-el.phi())/el.getResPhi()>>hElRelDevAngleResPhi");
  cElRes->cd(8);
  Events->Draw("(elMoved.theta()-el.theta())/el.getResTheta()>>hElRelDevAngleResTheta");
  cElRes->cd(9);
  Events->Draw("(elMoved.eta()-el.eta())/el.getResEta()>>hElRelDevAngleResEta");
  cElRes->cd(10);
  Events->Draw("(elMoved.phi()-el.phi())/el.getResPhi():el.getResPhi()>>hElRelDevResPhi");
  cElRes->cd(11);
  Events->Draw("(elMoved.theta()-el.theta())/el.getResTheta():el.getResTheta()>>hElRelDevResTheta");
  cElRes->cd(12);
  Events->Draw("(elMoved.eta()-el.eta())/el.getResEta():el.getResEta()>>hElRelDevResEta");

  // Draw muon angles                    
  TH1D* hMuPhi        = new TH1D("hMuPhi"       ,";#phi;muons;"  ,bins,phiXmin  ,phiXmax);
  TH1D* hMuMovedPhi   = new TH1D("hMuMovedPhi"  ,";#phi;muons;"  ,bins,phiXmin  ,phiXmax);
  TH1D* hMuTheta      = new TH1D("hMuTheta"     ,";#theta;muons;",bins,thetaXmin,thetaXmax);
  TH1D* hMuMovedTheta = new TH1D("hMuMovedTheta",";#theta;muons;",bins,thetaXmin,thetaXmax);
  TH1D* hMuEta        = new TH1D("hMuEta"       ,";#eta;muons;"  ,bins,etaXmin  ,etaXmax);
  TH1D* hMuMovedEta   = new TH1D("hMuMovedEta"  ,";#eta;muons;"  ,bins,etaXmin  ,etaXmax);
  TH2D* hMuPhiMoved   = new TH2D("hMuPhiMoved"  ,";#phi;#phi_{new};electrons"    ,bins,phiXmin  ,phiXmax  ,bins,phiXmin  ,phiXmax);
  TH2D* hMuThetaMoved = new TH2D("hMuThetaMoved",";#theta;#theta_{new};electrons",bins,thetaXmin,thetaXmax,bins,thetaXmin,thetaXmax);
  TH2D* hMuEtaMoved   = new TH2D("hMuEtaMoved"  ,";#eta;#eta_{new};electrons"    ,bins,etaXmin  ,etaXmax  ,bins,etaXmin  ,etaXmax);
  TH2D* hMuRelDevPhi   = new TH2D("hMuRelDevPhi"  ,";#phi;#phi_{new}-#phi;muons"      ,bins,phiXmin  ,phiXmax  ,bins,-0.005,0.005);
  TH2D* hMuRelDevTheta = new TH2D("hMuRelDevTheta",";#theta;#theta_{new}-#theta;muons",bins,thetaXmin,thetaXmax,bins,-0.005,0.005);
  TH2D* hMuRelDevEta   = new TH2D("hMuRelDevEta"  ,";#eta;#eta_{new}-#eta;muons"      ,bins,etaXmin  ,etaXmax  ,bins,-0.005,0.005);
  hMuPhi->SetLineColor(kRed);
  hMuPhi->SetFillColor(kYellow);
  hMuMovedPhi->SetLineWidth(2);
  hMuTheta->SetLineColor(kRed);
  hMuTheta->SetFillColor(kYellow);
  hMuMovedTheta->SetLineWidth(2);
  hMuEta->SetLineColor(kRed);
  hMuEta->SetFillColor(kYellow);
  hMuMovedEta->SetLineWidth(2);
  hMuPhiMoved->SetMarkerSize(0.1);  
  hMuThetaMoved->SetMarkerSize(0.1);
  hMuEtaMoved->SetMarkerSize(0.1);  
  hMuRelDevPhi->SetMarkerSize(0.1);  
  hMuRelDevTheta->SetMarkerSize(0.1);
  hMuRelDevEta->SetMarkerSize(0.1);  
  TCanvas* cMuAngles = new TCanvas("cMuAngles","Muon Angles");
  cMuAngles->Divide(3,3);
  cMuAngles->cd(1);
  Events->Draw("mu.phi()>>hMuPhi");
  Events->Draw("muMoved.phi()>>hMuMovedPhi","","Same");
  cMuAngles->cd(2);
  Events->Draw("mu.theta()>>hMuTheta");
  Events->Draw("muMoved.theta()>>hMuMovedTheta","","Same");
  cMuAngles->cd(3);
  Events->Draw("mu.eta()>>hMuEta");
  Events->Draw("muMoved.eta()>>hMuMovedEta","","Same");
  cMuAngles->cd(4);
  Events->Draw("muMoved.phi():mu.phi()>>hMuPhiMoved");
  cMuAngles->cd(5);
  Events->Draw("muMoved.theta():mu.theta()>>hMuThetaMoved");
  cMuAngles->cd(6);
  Events->Draw("muMoved.eta():mu.eta()>>hMuEtaMoved");
  cMuAngles->cd(7);
  Events->Draw("muMoved.phi()-mu.phi():mu.phi()>>hMuRelDevPhi");
  cMuAngles->cd(8);
  Events->Draw("muMoved.theta()-mu.theta():mu.theta()>>hMuRelDevTheta");
  cMuAngles->cd(9);
  Events->Draw("muMoved.eta()-mu.eta():mu.eta()>>hMuRelDevEta");
  // Draw muon resolutions                    
  TH1D* hMuResPhi   = new TH1D("hMuResPhi"  ,";#sigma_{#phi};muons;"  ,bins,0.,0.0025);
  TH1D* hMuResTheta = new TH1D("hMuResTheta",";#sigma_{#theta};muons;",bins,0.,0.001);
  TH1D* hMuResEta   = new TH1D("hMuResEta"  ,";#sigma_{#eta};muons;"  ,bins,0.,0.001);
  TH2D* hMuResAnglePhi   = new TH2D("hMuResAnglePhi"  ,";#theta;#sigma_{#phi};muons"   ,bins,thetaXmin,thetaXmax,bins,0.,0.0025);
  TH2D* hMuResAngleTheta = new TH2D("hMuResAngleTheta",";#theta;#sigma_{#theta};muons;",bins,thetaXmin,thetaXmax,bins,0.,0.001);
  TH2D* hMuResAngleEta   = new TH2D("hMuResAngleEta"  ,";#theta;#sigma_{#eta};muons;"  ,bins,thetaXmin,thetaXmax,bins,0.,0.001);
  TH1D* hMuRelDevAngleResPhi   = new TH1D("hMuRelDevAngleResPhi"  ,";#frac{#phi_{new}-#phi}{#sigma_{#phi}};muons;"      ,bins,-10.,10.);
  TH1D* hMuRelDevAngleResTheta = new TH1D("hMuRelDevAngleResTheta",";#frac{#theta_{new}-#theta}{#sigma_{#theta}};muons;",bins,-10.,10.);
  TH1D* hMuRelDevAngleResEta   = new TH1D("hMuRelDevAngleResEta"  ,";#frac{#eta_{new}-#eta}{#sigma_{#eta}};muons;"      ,bins,-10.,10.);
  TH2D* hMuRelDevResPhi   = new TH2D("hMuRelDevResPhi"  ,";#sigma_{#phi};#frac{#phi_{new}-#phi}{#sigma_{#phi}};muons"        ,bins,0.,0.0025,bins,-10.,10.);
  TH2D* hMuRelDevResTheta = new TH2D("hMuRelDevResTheta",";#sigma_{#theta};#frac{#theta_{new}-#theta}{#sigma_{#theta}};muons",bins,0.,0.001 ,bins,-10.,10.);
  TH2D* hMuRelDevResEta   = new TH2D("hMuRelDevResEta"  ,";#sigma_{#eta};#frac{#eta_{new}-#eta}{#sigma_{#eta}};muons"        ,bins,0.,0.001 ,bins,-10.,10.);
  hMuResAnglePhi->SetMarkerSize(0.1);  
  hMuResAngleTheta->SetMarkerSize(0.1);
  hMuResAngleEta->SetMarkerSize(0.1);  
  hMuRelDevResPhi->SetMarkerSize(0.1);  
  hMuRelDevResTheta->SetMarkerSize(0.1);
  hMuRelDevResEta->SetMarkerSize(0.1);  
  TCanvas* cMuRes= new TCanvas("cMuRes","Muon Resolutions");
  cMuRes->Divide(3,4);
  cMuRes->cd(1);
  Events->Draw("mu.getResPhi()>>hMuResPhi");
  cMuRes->cd(2);
  Events->Draw("mu.getResTheta()>>hMuResTheta");
  cMuRes->cd(3);
  Events->Draw("mu.getResEta()>>hMuResEta");
  cMuRes->cd(4);
  Events->Draw("mu.getResPhi():mu.theta()>>hMuResAnglePhi");
  cMuRes->cd(5);
  Events->Draw("mu.getResTheta():mu.theta()>>hMuResAngleTheta");
  cMuRes->cd(6);
  Events->Draw("mu.getResEta():mu.theta()>>hMuResAngleEta");
  cMuRes->cd(7);
  Events->Draw("(muMoved.phi()-mu.phi())/mu.getResPhi()>>hMuRelDevAngleResPhi");
  cMuRes->cd(8);
  Events->Draw("(muMoved.theta()-mu.theta())/mu.getResTheta()>>hMuRelDevAngleResTheta");
  cMuRes->cd(9);
  Events->Draw("(muMoved.eta()-mu.eta())/mu.getResEta()>>hMuRelDevAngleResEta");
  cMuRes->cd(10);
  Events->Draw("(muMoved.phi()-mu.phi())/mu.getResPhi():mu.getResPhi()>>hMuRelDevResPhi");
  cMuRes->cd(11);
  Events->Draw("(muMoved.theta()-mu.theta())/mu.getResTheta():mu.getResTheta()>>hMuRelDevResTheta");
  cMuRes->cd(12);
  Events->Draw("(muMoved.eta()-mu.eta())/mu.getResEta():mu.getResEta()>>hMuRelDevResEta");

//   // Draw tau angles                    
//   TH1D* hTauPhi        = new TH1D("hTauPhi"       ,";#phi;taus;"  ,bins,phiXmin  ,phiXmax);
//   TH1D* hTauMovedPhi   = new TH1D("hTauMovedPhi"  ,";#phi;taus;"  ,bins,phiXmin  ,phiXmax);
//   TH1D* hTauTheta      = new TH1D("hTauTheta"     ,";#theta;taus;",bins,thetaXmin,thetaXmax);
//   TH1D* hTauMovedTheta = new TH1D("hTauMovedTheta",";#theta;taus;",bins,thetaXmin,thetaXmax);
//   TH1D* hTauEta        = new TH1D("hTauEta"       ,";#eta;taus;"  ,bins,etaXmin  ,etaXmax);
//   TH1D* hTauMovedEta   = new TH1D("hTauMovedEta"  ,";#eta;taus;"  ,bins,etaXmin  ,etaXmax);
//   TH2D* hTauPhiMoved   = new TH2D("hTauPhiMoved"  ,";#phi;#phi_{new};electrons"    ,bins,phiXmin  ,phiXmax  ,bins,phiXmin  ,phiXmax);
//   TH2D* hTauThetaMoved = new TH2D("hTauThetaMoved",";#theta;#theta_{new};electrons",bins,thetaXmin,thetaXmax,bins,thetaXmin,thetaXmax);
//   TH2D* hTauEtaMoved   = new TH2D("hTauEtaMoved"  ,";#eta;#eta_{new};electrons"    ,bins,etaXmin  ,etaXmax  ,bins,etaXmin  ,etaXmax);
//   TH2D* hTauRelDevPhi   = new TH2D("hTauRelDevPhi"  ,";#phi;#phi_{new}-#phi;taus"      ,bins,phiXmin  ,phiXmax  ,bins,-0.005,0.005);
//   TH2D* hTauRelDevTheta = new TH2D("hTauRelDevTheta",";#theta;#theta_{new}-#theta;taus",bins,thetaXmin,thetaXmax,bins,-0.005,0.005);
//   TH2D* hTauRelDevEta   = new TH2D("hTauRelDevEta"  ,";#eta;#eta_{new}-#eta;taus"      ,bins,etaXmin  ,etaXmax  ,bins,-0.005,0.005);
//   hTauPhi->SetLineColor(kRed);
//   hTauPhi->SetFillColor(kYellow);
//   hTauMovedPhi->SetLineWidth(2);
//   hTauTheta->SetLineColor(kRed);
//   hTauTheta->SetFillColor(kYellow);
//   hTauMovedTheta->SetLineWidth(2);
//   hTauEta->SetLineColor(kRed);
//   hTauEta->SetFillColor(kYellow);
//   hTauMovedEta->SetLineWidth(2);
//   hTauPhiMoved->SetMarkerSize(0.1);  
//   hTauThetaMoved->SetMarkerSize(0.1);
//   hTauEtaMoved->SetMarkerSize(0.1);  
//   hTauRelDevPhi->SetMarkerSize(0.1);  
//   hTauRelDevTheta->SetMarkerSize(0.1);
//   hTauRelDevEta->SetMarkerSize(0.1);  
//   TCanvas* cTauAngles = new TCanvas("cTauAngles","Tau Angles");
//   cTauAngles->Divide(3,3);
//   cTauAngles->cd(1);
//   Events->Draw("tau.phi()>>hTauPhi");
//   Events->Draw("tauMoved.phi()>>hTauMovedPhi","","Same");
//   cTauAngles->cd(2);
//   Events->Draw("tau.theta()>>hTauTheta");
//   Events->Draw("tauMoved.theta()>>hTauMovedTheta","","Same");
//   cTauAngles->cd(3);
//   Events->Draw("tau.eta()>>hTauEta");
//   Events->Draw("tauMoved.eta()>>hTauMovedEta","","Same");
//   cTauAngles->cd(4);
//   Events->Draw("tauMoved.phi():tau.phi()>>hTauPhiMoved");
//   cTauAngles->cd(5);
//   Events->Draw("tauMoved.theta():tau.theta()>>hTauThetaMoved");
//   cTauAngles->cd(6);
//   Events->Draw("tauMoved.eta():tau.eta()>>hTauEtaMoved");
//   cTauAngles->cd(7);
//   Events->Draw("tauMoved.phi()-tau.phi():tau.phi()>>hTauRelDevPhi");
//   cTauAngles->cd(8);
//   Events->Draw("tauMoved.theta()-tau.theta():tau.theta()>>hTauRelDevTheta");
//   cTauAngles->cd(9);
//   Events->Draw("tauMoved.eta()-tau.eta():tau.eta()>>hTauRelDevEta");
//   // Draw tau resolutions                    
//   TH1D* hTauResPhi   = new TH1D("hTauResPhi"  ,";#sigma_{#phi};taus;"  ,bins,0.,0.0025);
//   TH1D* hTauResTheta = new TH1D("hTauResTheta",";#sigma_{#theta};taus;",bins,0.,0.001);
//   TH1D* hTauResEta   = new TH1D("hTauResEta"  ,";#sigma_{#eta};taus;"  ,bins,0.,0.001);
//   TH2D* hTauResAnglePhi   = new TH2D("hTauResAnglePhi"  ,";#theta;#sigma_{#phi};taus"   ,bins,thetaXmin,thetaXmax,bins,0.,0.0025);
//   TH2D* hTauResAngleTheta = new TH2D("hTauResAngleTheta",";#theta;#sigma_{#theta};taus;",bins,thetaXmin,thetaXmax,bins,0.,0.001);
//   TH2D* hTauResAngleEta   = new TH2D("hTauResAngleEta"  ,";#theta;#sigma_{#eta};taus;"  ,bins,thetaXmin,thetaXmax,bins,0.,0.001);
//   TH1D* hTauRelDevAngleResPhi   = new TH1D("hTauRelDevAngleResPhi"  ,";#frac{#phi_{new}-#phi}{#sigma_{#phi}};taus;"      ,bins,-10.,10.);
//   TH1D* hTauRelDevAngleResTheta = new TH1D("hTauRelDevAngleResTheta",";#frac{#theta_{new}-#theta}{#sigma_{#theta}};taus;",bins,-10.,10.);
//   TH1D* hTauRelDevAngleResEta   = new TH1D("hTauRelDevAngleResEta"  ,";#frac{#eta_{new}-#eta}{#sigma_{#eta}};taus;"      ,bins,-10.,10.);
//   TH2D* hTauRelDevResPhi   = new TH2D("hTauRelDevResPhi"  ,";#sigma_{#phi};#frac{#phi_{new}-#phi}{#sigma_{#phi}};taus"        ,bins,0.,0.0025,bins,-10.,10.);
//   TH2D* hTauRelDevResTheta = new TH2D("hTauRelDevResTheta",";#sigma_{#theta};#frac{#theta_{new}-#theta}{#sigma_{#theta}};taus",bins,0.,0.001 ,bins,-10.,10.);
//   TH2D* hTauRelDevResEta   = new TH2D("hTauRelDevResEta"  ,";#sigma_{#eta};#frac{#eta_{new}-#eta}{#sigma_{#eta}};taus"        ,bins,0.,0.001 ,bins,-10.,10.);
//   hTauResAnglePhi->SetMarkerSize(0.1);  
//   hTauResAngleTheta->SetMarkerSize(0.1);
//   hTauResAngleEta->SetMarkerSize(0.1);  
//   hTauRelDevResPhi->SetMarkerSize(0.1);  
//   hTauRelDevResTheta->SetMarkerSize(0.1);
//   hTauRelDevResEta->SetMarkerSize(0.1);  
//   TCanvas* cTauRes= new TCanvas("cTauRes","Tau Resolutions");
//   cTauRes->Divide(3,4);
//   cTauRes->cd(1);
//   Events->Draw("tau.getResPhi()>>hTauResPhi");
//   cTauRes->cd(2);
//   Events->Draw("tau.getResTheta()>>hTauResTheta");
//   cTauRes->cd(3);
//   Events->Draw("tau.getResEta()>>hTauResEta");
//   cTauRes->cd(4);
//   Events->Draw("tau.getResPhi():tau.theta()>>hTauResAnglePhi");
//   cTauRes->cd(5);
//   Events->Draw("tau.getResTheta():tau.theta()>>hTauResAngleTheta");
//   cTauRes->cd(6);
//   Events->Draw("tau.getResEta():tau.theta()>>hTauResAngleEta");
//   cTauRes->cd(7);
//   Events->Draw("(tauMoved.phi()-tau.phi())/tau.getResPhi()>>hTauRelDevAngleResPhi");
//   cTauRes->cd(8);
//   Events->Draw("(tauMoved.theta()-tau.theta())/tau.getResTheta()>>hTauRelDevAngleResTheta");
//   cTauRes->cd(9);
//   Events->Draw("(tauMoved.eta()-tau.eta())/tau.getResEta()>>hTauRelDevAngleResEta");
//   cTauRes->cd(10);
//   Events->Draw("(tauMoved.phi()-tau.phi())/tau.getResPhi():tau.getResPhi()>>hTauRelDevResPhi");
//   cTauRes->cd(11);
//   Events->Draw("(tauMoved.theta()-tau.theta())/tau.getResTheta():tau.getResTheta()>>hTauRelDevResTheta");
//   cTauRes->cd(12);
//   Events->Draw("(tauMoved.eta()-tau.eta())/tau.getResEta():tau.getResEta()>>hTauRelDevResEta");

  // Draw jet angles                    
  TH1D* hJetPhi        = new TH1D("hJetPhi"       ,";#phi;jets;"  ,bins,phiXmin  ,phiXmax);
  TH1D* hJetMovedPhi   = new TH1D("hJetMovedPhi"  ,";#phi;jets;"  ,bins,phiXmin  ,phiXmax);
  TH1D* hJetTheta      = new TH1D("hJetTheta"     ,";#theta;jets;",bins,thetaXmin,thetaXmax);
  TH1D* hJetMovedTheta = new TH1D("hJetMovedTheta",";#theta;jets;",bins,thetaXmin,thetaXmax);
  TH1D* hJetEta        = new TH1D("hJetEta"       ,";#eta;jets;"  ,bins,etaXmin  ,etaXmax);
  TH1D* hJetMovedEta   = new TH1D("hJetMovedEta"  ,";#eta;jets;"  ,bins,etaXmin  ,etaXmax);
  TH2D* hJetPhiMoved   = new TH2D("hJetPhiMoved"  ,";#phi;#phi_{new};electrons"    ,bins,phiXmin  ,phiXmax  ,bins,phiXmin  ,phiXmax);
  TH2D* hJetThetaMoved = new TH2D("hJetThetaMoved",";#theta;#theta_{new};electrons",bins,thetaXmin,thetaXmax,bins,thetaXmin,thetaXmax);
  TH2D* hJetEtaMoved   = new TH2D("hJetEtaMoved"  ,";#eta;#eta_{new};electrons"    ,bins,etaXmin  ,etaXmax  ,bins,etaXmin  ,etaXmax);
  TH2D* hJetRelDevPhi   = new TH2D("hJetRelDevPhi"  ,";#phi;#phi_{new}-#phi;jets"      ,bins,phiXmin  ,phiXmax  ,bins,-TMath::Pi()   ,TMath::Pi());
  TH2D* hJetRelDevTheta = new TH2D("hJetRelDevTheta",";#theta;#theta_{new}-#theta;jets",bins,thetaXmin,thetaXmax,bins,-TMath::Pi()/2.,TMath::Pi()/2.);
  TH2D* hJetRelDevEta   = new TH2D("hJetRelDevEta"  ,";#eta;#eta_{new}-#eta;jets"      ,bins,etaXmin  ,etaXmax  ,bins,            -5.,            5.);
  hJetPhi->SetLineColor(kRed);
  hJetPhi->SetFillColor(kYellow);
  hJetMovedPhi->SetLineWidth(2);
  hJetTheta->SetLineColor(kRed);
  hJetTheta->SetFillColor(kYellow);
  hJetMovedTheta->SetLineWidth(2);
  hJetEta->SetLineColor(kRed);
  hJetEta->SetFillColor(kYellow);
  hJetMovedEta->SetLineWidth(2);
  hJetPhiMoved->SetMarkerSize(0.1);  
  hJetThetaMoved->SetMarkerSize(0.1);
  hJetEtaMoved->SetMarkerSize(0.1);  
  hJetRelDevPhi->SetMarkerSize(0.1);  
  hJetRelDevTheta->SetMarkerSize(0.1);
  hJetRelDevEta->SetMarkerSize(0.1);  
  TCanvas* cJetAngles = new TCanvas("cJetAngles","Jet Angles");
  cJetAngles->Divide(3,3);
  cJetAngles->cd(1);
  Events->Draw("jet.phi()>>hJetPhi");
  Events->Draw("jetMoved.phi()>>hJetMovedPhi","","Same");
  cJetAngles->cd(2);
  Events->Draw("jet.theta()>>hJetTheta");
  Events->Draw("jetMoved.theta()>>hJetMovedTheta","","Same");
  cJetAngles->cd(3);
  Events->Draw("jet.eta()>>hJetEta");
  Events->Draw("jetMoved.eta()>>hJetMovedEta","","Same");
  cJetAngles->cd(4);
  Events->Draw("jetMoved.phi():jet.phi()>>hJetPhiMoved");
  cJetAngles->cd(5);
  Events->Draw("jetMoved.theta():jet.theta()>>hJetThetaMoved");
  cJetAngles->cd(6);
  Events->Draw("jetMoved.eta():jet.eta()>>hJetEtaMoved");
  cJetAngles->cd(7);
  Events->Draw("jetMoved.phi()-jet.phi():jet.phi()>>hJetRelDevPhi");
  cJetAngles->cd(8);
  Events->Draw("jetMoved.theta()-jet.theta():jet.theta()>>hJetRelDevTheta");
  cJetAngles->cd(9);
  Events->Draw("jetMoved.eta()-jet.eta():jet.eta()>>hJetRelDevEta");
  // Draw jet resolutions                    
  TH1D* hJetResPhi   = new TH1D("hJetResPhi"  ,";#sigma_{#phi};jets;"  ,bins,0.,0.2);
  TH1D* hJetResTheta = new TH1D("hJetResTheta",";#sigma_{#theta};jets;",bins,0.,0.2);
  TH1D* hJetResEta   = new TH1D("hJetResEta"  ,";#sigma_{#eta};jets;"  ,bins,0.,0.2);
  TH2D* hJetResAnglePhi   = new TH2D("hJetResAnglePhi"  ,";#theta;#sigma_{#phi};jets"   ,bins,thetaXmin,thetaXmax,bins,0.,0.2);
  TH2D* hJetResAngleTheta = new TH2D("hJetResAngleTheta",";#theta;#sigma_{#theta};jets;",bins,thetaXmin,thetaXmax,bins,0.,0.2);
  TH2D* hJetResAngleEta   = new TH2D("hJetResAngleEta"  ,";#theta;#sigma_{#eta};jets;"  ,bins,thetaXmin,thetaXmax,bins,0.,0.2);
  TH1D* hJetRelDevAngleResPhi   = new TH1D("hJetRelDevAngleResPhi"  ,";#frac{#phi_{new}-#phi}{#sigma_{#phi}};jets;"      ,bins,-100.,100.);
  TH1D* hJetRelDevAngleResTheta = new TH1D("hJetRelDevAngleResTheta",";#frac{#theta_{new}-#theta}{#sigma_{#theta}};jets;",bins,-100.,100.);
  TH1D* hJetRelDevAngleResEta   = new TH1D("hJetRelDevAngleResEta"  ,";#frac{#eta_{new}-#eta}{#sigma_{#eta}};jets;"      ,bins,-100.,100.);
  TH2D* hJetRelDevResPhi   = new TH2D("hJetRelDevResPhi"  ,";#sigma_{#phi};#frac{#phi_{new}-#phi}{#sigma_{#phi}};jets"        ,bins,0.,0.2,bins,-100.,100.);
  TH2D* hJetRelDevResTheta = new TH2D("hJetRelDevResTheta",";#sigma_{#theta};#frac{#theta_{new}-#theta}{#sigma_{#theta}};jets",bins,0.,0.2,bins,-100.,100.);
  TH2D* hJetRelDevResEta   = new TH2D("hJetRelDevResEta"  ,";#sigma_{#eta};#frac{#eta_{new}-#eta}{#sigma_{#eta}};jets"        ,bins,0.,0.2,bins,-100.,100.);
  hJetResAnglePhi->SetMarkerSize(0.1);  
  hJetResAngleTheta->SetMarkerSize(0.1);
  hJetResAngleEta->SetMarkerSize(0.1);  
  hJetRelDevResPhi->SetMarkerSize(0.1);  
  hJetRelDevResTheta->SetMarkerSize(0.1);
  hJetRelDevResEta->SetMarkerSize(0.1);  
  TCanvas* cJetRes= new TCanvas("cJetRes","Jet Resolutions");
  cJetRes->Divide(3,4);
  cJetRes->cd(1);
  Events->Draw("jet.getResPhi()>>hJetResPhi");
  cJetRes->cd(2);
  Events->Draw("jet.getResTheta()>>hJetResTheta");
  cJetRes->cd(3);
  Events->Draw("jet.getResEta()>>hJetResEta");
  cJetRes->cd(4);
  Events->Draw("jet.getResPhi():jet.theta()>>hJetResAnglePhi");
  cJetRes->cd(5);
  Events->Draw("jet.getResTheta():jet.theta()>>hJetResAngleTheta");
  cJetRes->cd(6);
  Events->Draw("jet.getResEta():jet.theta()>>hJetResAngleEta");
  cJetRes->cd(7);
  Events->Draw("(jetMoved.phi()-jet.phi())/jet.getResPhi()>>hJetRelDevAngleResPhi");
  cJetRes->cd(8);
  Events->Draw("(jetMoved.theta()-jet.theta())/jet.getResTheta()>>hJetRelDevAngleResTheta");
  cJetRes->cd(9);
  Events->Draw("(jetMoved.eta()-jet.eta())/jet.getResEta()>>hJetRelDevAngleResEta");
  cJetRes->cd(10);
  Events->Draw("(jetMoved.phi()-jet.phi())/jet.getResPhi():jet.getResPhi()>>hJetRelDevResPhi");
  cJetRes->cd(11);
  Events->Draw("(jetMoved.theta()-jet.theta())/jet.getResTheta():jet.getResTheta()>>hJetRelDevResTheta");
  cJetRes->cd(12);
  Events->Draw("(jetMoved.eta()-jet.eta())/jet.getResEta():jet.getResEta()>>hJetRelDevResEta");

  // Draw met angles                    
  TH1D* hMetPhi      = new TH1D("hMetPhi"     ,";#phi;mets;",bins,phiXmin,phiXmax);
  TH1D* hMetMovedPhi = new TH1D("hMetMovedPhi",";#phi;mets;",bins,phiXmin,phiXmax);
  TH2D* hMetPhiMoved = new TH2D("hMetPhiMoved",";#phi;#phi_{new};mets",bins,phiXmin,phiXmax,bins,phiXmin,phiXmax);
  TH2D* hMetRelDevPhi = new TH2D("hMetRelDevPhi",";#phi;#phi_{new}-#phi;mets",bins,phiXmin,phiXmax,bins,-0.005,0.005);
  hMetPhi->SetLineColor(kRed);
  hMetPhi->SetFillColor(kYellow);
  hMetMovedPhi->SetLineWidth(2);
  hMetPhiMoved->SetMarkerSize(0.1);  
  hMetRelDevPhi->SetMarkerSize(0.1);  
  TCanvas* cMetAngles = new TCanvas("cMetAngles","MET Angles");
  cMetAngles->Divide(2,2);
  cMetAngles->cd(1);
  Events->Draw("met.phi()>>hMetPhi");
  Events->Draw("metMoved.phi()>>hMetMovedPhi","","Same");
  cMetAngles->cd(2);
  cMetAngles->cd(3);
  Events->Draw("metMoved.phi():met.phi()>>hMetPhiMoved");
  cMetAngles->cd(4);
  Events->Draw("metMoved.phi()-met.phi():met.phi()");
  // Draw met resolutions                    
  TH1D* hMetResPhi = new TH1D("hMetResPhi",";#sigma_{#phi};mets;",bins,0.,0.0025);
  TH2D* hMetResAnglePhi = new TH2D("hMetResAnglePhi",";#theta;#sigma_{#phi};mets",bins,thetaXmin,thetaXmax,bins,0.,0.0025);
  TH1D* hMetRelDevAngleResPhi = new TH1D("hMetRelDevAngleResPhi",";#frac{#phi_{new}-#phi}{#sigma_{#phi}};mets;",bins,-10.,10.);
  TH2D* hMetRelDevResPhi = new TH2D("hMetRelDevResPhi",";#sigma_{#phi};#frac{#phi_{new}-#phi}{#sigma_{#phi}};mets",bins,0.,0.0025,bins,-10.,10.);
  hMetResAnglePhi->SetMarkerSize(0.1);  
  hMetRelDevResPhi->SetMarkerSize(0.1);  
  TCanvas* cMetRes= new TCanvas("cMetRes","MET Resolutions");
  cMetRes->Divide(2,2);
  cMetRes->cd(1);
  Events->Draw("met.getResPhi()");
  cMetRes->cd(2);
  Events->Draw("met.getResPhi():met.theta()");
  cMetRes->cd(3);
  Events->Draw("(metMoved.phi()-met.phi())/met.getResPhi()");
  cMetRes->cd(4);
  Events->Draw("(metMoved.phi()-met.phi())/met.getResPhi():met.getResPhi()");

  // come back home
  myCanvas  ->cd(); 
  gDirectory->cd(dirBase);

}  